import { test, expect, type Page } from '@playwright/test';

const PAGE_URL = '/hub/library/information-request-list';

// Section anchor IDs are auto-generated by Astro's markdown loader from h2 text.
// Em-dashes collapse to double-dashes via github-slugger — matches the rendered IDs
// in dist/client/hub/library/information-request-list/index.html.
const EXPECTED_SECTION_IDS = [
  'how-to-use-this-list',
  '00--engagement-basics',
  '01--product',
  '02--software-architecture',
  '03--infrastructure--operations',
  '04--sdlc',
  '05--data-analytics--ai',
  '06--security',
  '07--people--organization',
  '08--corporate-it',
  '09--governance--compliance',
] as const;

// Attribute-form selectors (`[id="…"]`) avoid CSS's restriction that bare ID
// selectors cannot start with a digit. The auto-generated slugs are derived from
// the leading section numbers (e.g. "00 — Engagement Basics" → "00--engagement-basics").
const headingByIdLocator = (page: Page, id: string) => page.locator(`h2[id="${id}"]`);
const tocAnchorLocator = (page: Page, id: string) => page.locator(`.toc a[href="#${id}"]`);

/**
 * Wait on the deepest shared element the test cases depend on — a known
 * section heading — not just the page container. See
 * src/docs/testing/TEST_BEST_PRACTICES.md § 25.
 */
async function gotoPage(page: Page): Promise<void> {
  await page.goto(PAGE_URL, { waitUntil: 'domcontentloaded' });
  await page.waitForSelector('h2[id="00--engagement-basics"]', { timeout: 10000 });
}

test.describe('Hub Library — Information Request List', () => {
  test('renders every section heading from the canonical article', async ({ page }) => {
    await gotoPage(page);

    for (const id of EXPECTED_SECTION_IDS) {
      await expect(headingByIdLocator(page, id)).toBeVisible();
    }
  });

  test('table of contents anchors match every rendered section heading', async ({ page }) => {
    await gotoPage(page);

    for (const id of EXPECTED_SECTION_IDS) {
      await expect(tocAnchorLocator(page, id)).toHaveCount(1);
    }
  });

  test('library index card navigates to the IRL page', async ({ page }) => {
    await page.goto('/hub/library', { waitUntil: 'domcontentloaded' });
    await page.waitForSelector('.brutal-gateway-card', { timeout: 10000 });

    await page.locator('a[href="/hub/library/information-request-list"]').first().click();

    await page.waitForURL(/\/hub\/library\/information-request-list\/?$/, { timeout: 10000 });
    await expect(headingByIdLocator(page, '00--engagement-basics')).toBeVisible();
  });

  test('back-link returns to the library index', async ({ page }) => {
    await gotoPage(page);

    const backLink = page.locator('a.back-link[href="/hub/library"]');
    await expect(backLink).toBeVisible();

    await backLink.click();
    await page.waitForURL(/\/hub\/library\/?$/, { timeout: 10000 });
  });

  test('first section heading scrolls into view when its TOC link is clicked', async ({ page }) => {
    await gotoPage(page);

    const targetId = '03--infrastructure--operations';
    await tocAnchorLocator(page, targetId).click();

    // Wait for the URL hash to update (signals the browser handled the in-page navigation).
    await page.waitForFunction((id) => window.location.hash === `#${id}`, targetId, {
      timeout: 5000,
    });

    // Behavioral check: the heading is in the viewport after navigation.
    await expect(headingByIdLocator(page, targetId)).toBeInViewport();
  });
});
