/**
 * Unit tests for the `AuthFailureReason` discriminator + the
 * `shouldCaptureAuthFailure` Sentry-gating predicate.
 *
 * Why this matters: every 401 from the Worker used to fire a Sentry event,
 * including the ones generated by bot probes (missing/empty/wrong-scheme
 * bearer). Those drowned out actionable failures — a real team-member with
 * a stale `MCP_KEY_<INITIALS>` produces an `invalid-token` reason, which
 * is the one we actually want to alert on. These tests pin the contract.
 *
 * The full bearer-auth behavior (header parsing, 401 envelopes, key
 * matching) is covered by the integration tests at
 * `tests/integration/auth.test.ts`; this file only asserts the new
 * `reason` field on `AuthFailure` and the predicate's classification.
 */

import { describe, it, expect } from 'vitest';
import {
  authenticate,
  shouldCaptureAuthFailure,
  type AuthFailureReason,
} from '../../../src/auth/bearer';

function makeRequest(authHeader: string | null): Request {
  const headers = new Headers();
  if (authHeader !== null) headers.set('Authorization', authHeader);
  return new Request('https://example.test/mcp', { method: 'POST', headers });
}

describe('AuthFailure.reason — discriminator on every 401 path', () => {
  it('reason: missing-header when Authorization header is absent', () => {
    const env = { MCP_KEY_RP: 'good-token' };
    const result = authenticate(makeRequest(null), env);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toBe<AuthFailureReason>('missing-header');
    }
  });

  it('reason: empty-token when only "Bearer" with no token follows', () => {
    const env = { MCP_KEY_RP: 'good-token' };
    const result = authenticate(makeRequest('Bearer '), env);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toBe<AuthFailureReason>('empty-token');
    }
  });

  it('reason: empty-token when value is whitespace-only after the scheme', () => {
    const env = { MCP_KEY_RP: 'good-token' };
    const result = authenticate(makeRequest('Bearer    '), env);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toBe<AuthFailureReason>('empty-token');
    }
  });

  it('reason: bad-scheme when scheme is not Bearer', () => {
    const env = { MCP_KEY_RP: 'good-token' };
    const result = authenticate(makeRequest('Basic abc123'), env);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toBe<AuthFailureReason>('bad-scheme');
    }
  });

  it('reason: invalid-token when bearer is well-formed but no key matches', () => {
    const env = { MCP_KEY_RP: 'good-token' };
    const result = authenticate(makeRequest('Bearer wrong-token'), env);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toBe<AuthFailureReason>('invalid-token');
    }
  });

  it('reason: malformed-scopes when the matched key has bad _SCOPES JSON', () => {
    const env = {
      MCP_KEY_RP: 'good-token',
      MCP_KEY_RP_SCOPES: 'not-valid-json',
    };
    const result = authenticate(makeRequest('Bearer good-token'), env);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.reason).toBe<AuthFailureReason>('malformed-scopes');
      // The 401 envelope still carries the explanatory message for
      // operators — only the `reason` discriminator is new.
      expect(result.bodyText).toMatch(/_SCOPES JSON/i);
    }
  });
});

describe('shouldCaptureAuthFailure — Sentry gating policy', () => {
  // The policy: capture only on reasons that imply a real client with a
  // misconfigured key (or an operator-side config error), NOT on reasons
  // that are characteristic of probe/scanner traffic.

  it('captures invalid-token (real client with stale config)', () => {
    expect(shouldCaptureAuthFailure('invalid-token')).toBe(true);
  });

  it('captures malformed-scopes (operator-side config error)', () => {
    expect(shouldCaptureAuthFailure('malformed-scopes')).toBe(true);
  });

  it('skips missing-header (probe behavior — real clients always send one)', () => {
    expect(shouldCaptureAuthFailure('missing-header')).toBe(false);
  });

  it('skips empty-token (probe behavior)', () => {
    expect(shouldCaptureAuthFailure('empty-token')).toBe(false);
  });

  it('skips bad-scheme (probe behavior)', () => {
    expect(shouldCaptureAuthFailure('bad-scheme')).toBe(false);
  });

  it('exhaustive: all 5 reasons have a defined classification', () => {
    // Regression net — if a new AuthFailureReason is added without updating
    // SENTRY_WORTHY_REASONS, this test won't catch it directly (it'll
    // default to false). The compiler will catch unhandled additions in
    // the switch-style test above, where each reason gets its own `it`.
    // This test exists to document the invariant: every reason must have
    // an explicit decision, not an implicit default.
    const all: AuthFailureReason[] = [
      'missing-header',
      'empty-token',
      'bad-scheme',
      'invalid-token',
      'malformed-scopes',
    ];
    for (const r of all) {
      const decision = shouldCaptureAuthFailure(r);
      expect(typeof decision).toBe('boolean');
    }
  });
});
