import { defineMiddleware } from 'astro:middleware';

/**
 * Astro middleware for SSR routes (Radar).
 *
 * vercel.json headers apply only to static assets served by Vercel's CDN.
 * SSR responses are generated by the server function and need headers
 * injected here. Mirrors the same security headers from vercel.json.
 *
 * **Discovery defense (added 2026-05-18)**: internal-only endpoints listed
 * in `INTERNAL_ENDPOINTS` are hidden from anonymous probes. Requests
 * without an `Authorization: Bearer <token>` header receive a silent 404
 * — the same response an actually-non-existent path returns — instead of
 * 405 / 401 / 503 from the route handler. Bots probing GitHub-discovered
 * endpoint paths see "no such endpoint" rather than confirmation that
 * the endpoint exists + which method is required.
 *
 * Real callers (the MCP Worker with the matching shared secret) reach
 * the route handler unchanged; the bearer-value comparison still happens
 * inside the route, so a bearer-present-but-wrong attempt still produces
 * a Sentry-captured 401 (actionable signal — likely Worker misconfig).
 *
 * This is the website-side analogue of the Worker's `isRoutedPath()`
 * allowlist (PR #141) — both implement the principle: probe-class auth
 * failures stay off the visible-error surface; only real misconfig fires.
 */

/**
 * Endpoints that should appear non-existent to anonymous traffic.
 * Listed by exact pathname match. Add a new entry here when introducing
 * any internal-only endpoint that should not be discoverable via
 * status-code probing.
 *
 * **Currently empty** post-BL-032.8 Phase B (PR #140, 2026-05-27) — the
 * sole prior entry `/api/inoreader/refresh` (BL-039 fallback endpoint)
 * was retired with the rest of the website-side Inoreader surface. The
 * defense mechanism is kept ready for the next internal-only endpoint.
 */
const INTERNAL_ENDPOINTS: ReadonlySet<string> = new Set();

function isAnonymousProbe(request: Request): boolean {
  const auth = request.headers.get('Authorization');
  if (!auth) return true;
  if (!auth.startsWith('Bearer ')) return true;
  // Empty / whitespace-only bearer after the scheme prefix — also probe-class.
  if (!auth.slice('Bearer '.length).trim()) return true;
  return false;
}

export const SECURITY_HEADERS: Record<string, string> = {
  'X-Frame-Options': 'DENY',
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
  'X-DNS-Prefetch-Control': 'on',
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'Content-Security-Policy': [
    "default-src 'none'",
    "script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://va.vercel-scripts.com https://cdn.vercel-insights.com",
    "connect-src 'self' https://www.googletagmanager.com https://www.google-analytics.com https://analytics.google.com https://www.google.com https://*.ingest.sentry.io https://*.ingest.us.sentry.io https://vitals.vercel-insights.com",
    "worker-src 'self' blob:",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' https: data:",
    "font-src 'self'",
    "frame-src 'self'",
    "frame-ancestors 'none'",
    "manifest-src 'self'",
    "form-action 'self'",
    "base-uri 'self'",
    'upgrade-insecure-requests',
  ].join('; '),
};

/**
 * Routes that must be embeddable in a SAME-ORIGIN iframe.
 *
 * The site-wide default is `X-Frame-Options: DENY` + `frame-ancestors 'none'`,
 * which forbids framing by every origin — including this one. A page whose only
 * purpose is to be embedded therefore renders as an empty frame, with no build
 * error and no console warning to explain it.
 *
 * `/brand/responsive-frame` is a `noindex` partial rendered exclusively inside
 * the brand page's Responsive Behavior section, at three viewport widths. It
 * holds no user data, no authenticated state and no actionable form, so relaxing
 * it to `'self'` gives an attacker nothing: a same-origin frame can only be
 * created by our own pages. Every other route keeps the strict default.
 *
 * Paths are stored without a trailing slash; the lookup normalizes.
 */
const SAME_ORIGIN_FRAMEABLE = new Set(['/brand/responsive-frame']);

export const onRequest = defineMiddleware(async (context, next) => {
  // Discovery defense for internal endpoints. See module docstring.
  // Runs BEFORE `next()` so the route handler doesn't execute on probes;
  // the function still gets invoked by Vercel (Astro middleware runs
  // in-function), but with O(set-lookup) overhead instead of full
  // route-handler work + Sentry-capture cost.
  if (INTERNAL_ENDPOINTS.has(context.url.pathname) && isAnonymousProbe(context.request)) {
    return new Response('Not Found', { status: 404 });
  }

  const response = await next();

  for (const [key, value] of Object.entries(SECURITY_HEADERS)) {
    // In dev mode, skip headers that break the HTTP dev server:
    // - HSTS causes browsers to cache localhost as HTTPS-only
    // - upgrade-insecure-requests upgrades http:// sub-resources to https://,
    //   which fails under mobile UA emulation (iPhone 12) in Playwright
    if (import.meta.env.DEV) {
      if (key === 'Strict-Transport-Security') continue;
      if (key === 'Content-Security-Policy') {
        // Depends on upgrade-insecure-requests being the last CSP directive.
        // If the directive order in SECURITY_HEADERS changes, update this.
        response.headers.set(key, value.replace('; upgrade-insecure-requests', ''));
        continue;
      }
    }
    response.headers.set(key, value);
  }

  // Narrow exception: routes that exist to be embedded same-origin. See the
  // SAME_ORIGIN_FRAMEABLE docblock — the site-wide default forbids framing by
  // every origin including our own, which silently breaks such a page.
  if (SAME_ORIGIN_FRAMEABLE.has(context.url.pathname.replace(/\/$/, ''))) {
    response.headers.set('X-Frame-Options', 'SAMEORIGIN');
    const csp = response.headers.get('Content-Security-Policy');
    if (csp) {
      response.headers.set(
        'Content-Security-Policy',
        csp.replace("frame-ancestors 'none'", "frame-ancestors 'self'")
      );
    }
  }

  return response;
});
